### ISSUE TITLE
Cannot change password: it doesn't work

### ISSUE THREAD

**Issue by PeopleInside** [azlux/Simple-URL-Shortener#13]
Hi,
I hope your day is going well 🌻

Thank you for this wonderful plugin!
After I setup the instance and created some link stored in my admin profile (already in production) I need change my password.

I log, I use the password change function inserting correctly the old and the new password but password is not changed.

I write to report the issue and also for asking how can I change password without loose my account and all existent links.
Thanks.

I'm using sqlite3

I find a program to read the sqlite3 database, i create a backup of the original database, I deleted my admin account from the database using the software. I edited config.php to allow again registration and recreated the admin account with the same username but the new password.

Turned off again registration from config.php and logged successfully and all my links still be where should be.

**Comment by azlux** [comment]
Hi,
Sorry I don't use this tool a lot anymore.
But after reading the code again, I see the issue.

During the account creation, I hash the password before adding it into the database : https://github.com/azlux/Simple-URL-Shortener/blob/master/login.php#L15-L16
But on the password change function, The two lines for hashing aren't here : https://github.com/azlux/Simple-URL-Shortener/blob/master/login.php#L56 , So It try to add the plaintext password into the database instead of the hashed one.

If you have already lost you access, you can do the step:
 - Execute the line into a php interpreter (available with `php -a`) : `echo password_hash("the-new-password-you-want", PASSWORD_BCRYPT, ['cost' => 12,]);` , this line hash your password.
 - Use the output and add it into the table `users`, column `password` into the database like this example: 
```sql
UPDATE `users` SET `password`='the-previous-output' WHERE `username`='your-admin-username-here' AND `admin`='1';
```

If you know how to code, you can submit a PR.

Best regards,
Az

**Comment by PeopleInside** [comment]
Hi and thanks for the reply!
I love this tool, it's easy to install, light and works well.

I tried some other open source but without positive success 😊

Unfortunately I'm a not a programmer so I cannot code to submit a PR.

Thank you for the fast and kind reply :-)

**Comment by PeopleInside** [comment]
Thank you <3
